#!/bin/sh
if [ -L $0 ] ; then
    BB_HOME=`readlink -f "$0" | xargs dirname`
else
    BB_HOME=${0%${0##*/}}
fi
cd $BB_HOME
LIBS=`find lib -name '*.jar' | paste -s -d : -`
GR_LIBS=Users/oliver/.m2/repository/org/springframework/spring-web/3.0.0.RC3/spring-web-3.0.0.RC3.jar:/Users/oliver/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:/Users/oliver/.m2/repository/org/springframework/spring-beans/3.0.0.RC3/spring-beans-3.0.0.RC3.jar:/Users/oliver/.m2/repository/org/springframework/spring-core/3.0.0.RC3/spring-core-3.0.0.RC3.jar:/Users/oliver/.m2/repository/org/springframework/spring-asm/3.0.0.RC3/spring-asm-3.0.0.RC3.jar:/Users/oliver/.m2/repository/commons-logging/commons-logging/1.0.4/commons-logging-1.0.4.jar:/Users/oliver/.m2/repository/org/springframework/spring-context/3.0.0.RC3/spring-context-3.0.0.RC3.jar:/Users/oliver/.m2/repository/org/springframework/spring-expression/3.0.0.RC3/spring-expression-3.0.0.RC3.jar:/Users/oliver/.m2/repository/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.jar:/Users/oliver/.m2/repository/commons-codec/commons-codec/1.2/commons-codec-1.2.jar:/Users/oliver/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.3.2/jackson-mapper-asl-1.3.2.jar:/Users/oliver/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.3.2/jackson-core-asl-1.3.2.jar:/Users/oliver/.m2/repository/org/apache/httpcomponents/httpclient/4.0.1/httpclient-4.0.1.jar:/Users/oliver/.m2/repository/org/apache/httpcomponents/httpcore/4.0.1/httpcore-4.0.1.jar:/Users/oliver/.m2/repository/ch/qos/logback/logback-classic/0.9.17/logback-classic-0.9.17.jar:/Users/oliver/.m2/repository/ch/qos/logback/logback-core/0.9.17/logback-core-0.9.17.jar:/Users/oliver/.m2/repository/org/slf4j/slf4j-api/1.5.8/slf4j-api-1.5.8.jar:/Users/oliver/.m2/repository/org/jdom/jdom/1.1/jdom-1.1.jar:/Users/oliver/.m2/repository/jaxen/jaxen/1.1.1/jaxen-1.1.1.jar:/Users/oliver/.m2/repository/dom4j/dom4j/1.6.1/dom4j-1.6.1.jar:/Users/oliver/.m2/repository/jdom/jdom/1.0/jdom-1.0.jar:/Users/oliver/.m2/repository/xml-apis/xml-apis/1.3.02/xml-apis-1.3.02.jar:/Users/oliver/.m2/repository/xom/xom/1.0/xom-1.0.jar:/Users/oliver/.m2/repository/commons-io/commons-io/1.4/commons-io-1.4.jar:/Users/oliver/devel/bb-plugins/google-reader-bridge/google-reader-client/target/google-reader-client-1.0-SNAPSHOT.jar:/Users/oliver/devel/bb-plugins/google-reader-bridge/plugin/target/google-reader-bridge-plugin-1.0-SNAPSHOT.jar


java -Djava.library.path=lib -Dsun.net.client.defaultConnectTimeout=30000 -Dsun.net.client.defaultReadTimeout=60000 -Dworking.folder=final -Drelease.type=stable -Dreport.errors -Dapple.laf.useScreenMenuBar=true -Xms256M -Xmx256M -XX:NewRatio=2 -XX:SurvivorRatio=3 -Xverify:none -cp blogbridge.jar:$LIBS:$GR_LIBS com.salas.bb.core.ApplicationLauncher
    
